### ISSUE TITLE
Feature request: see status when wrong code is entered

### ISSUE THREAD

**Issue by techoguy** [dknowles2/ha-schlage#108]
Hi @dknowles2, great work on this integration! It works great for me so far. Thanks for all the work!

One thing I was curious about, is there a way to see the status when a wrong pin has been entered and the keypad has been temporarily disabled? The picture shows what it looks like in the app. I would like to make an automation when this happens. 

![Screenshot_20230810-205938](https://github.com/dknowles2/ha-schlage/assets/7158936/87a12eb0-6fc9-4a59-99e0-f801990c858d)

**Comment by techoguy** [comment]
Okay great! Thanks for adding it and have fun traveling!

**Comment by dknowles2** [comment]
This will be in Home Assistant `2023.10`: https://github.com/home-assistant/core/pull/99637
