### ISSUE TITLE
Removal of this custom integration

### ISSUE THREAD

**Issue by UncleanTurakina** [dknowles2/ha-schlage#123]
Hi,

I have ried to remove this custom integration but ended up corputing my HA install and eventually had to cobble together a previous backup and  reconfigure many subsequnt changes.  And the Schlage custom isntall is still there.  Can you please detailed but simple instruction to remove the custom integration without corrupting the whole system.

Thanks in advance,
NewBee

**Comment by dknowles2** [comment]
(Assuming you've installed via HACS)

1. Go to the "HACS" section in HA
2. Find the Schlage integration
3. Click the three dots on the right-hand side
4. Click "Remove"
5. Restart Home Assistant

If that doesn't work, you may need to first:

1. Go to "Settings" > "Devices & Services"
2. Click "Schlage"
3. Click the three dots on the right of "Integration entries"
4. Click "Delete"

That will remove the Schlage entries from your HA database, which will make it safe to remove the integration from HACS.

**Comment by UncleanTurakina** [comment]
Hi David,

That worked thank you.  Thanks for the great addon in the first place as well.

Kind regards,
Ian.
