### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by WorldOfMaze** [dknowles2/ha-schlage#130]
I have installed the integration via HACS, restarted the server and added the integration.  When the wizard appears, it asks for `username` and `password`.  After I enter the Schlege Home credentials, I get a message saying `Invalid authentication`.  I have confirmed that these credentials work with the Schlege Home app and used the same credentials to add the lock to Google Home.

Any idea what I might be doing wrong?

Thanks.

**Comment by dknowles2** [comment]
Please remove the integration from HACS. This custom integration is no longer supported, as there is native support in Home Assistant.
