### ISSUE TITLE
Feature Request: Getting names of Users who entered the Pin code

### ISSUE THREAD

**Issue by SensehacK** [dknowles2/ha-schlage#53]
first of all, thank you for your project. Helped me have quick integration with Home assistant.

I would like to know if its possible to have information extracted from Schlage about who entered the house 

eg Person A, Kid or Person B or Guest. Depending on what passcode it was set.

That can trigger other automation in Home assistant to set different thermostat temperatures or light scenes or music preferences.

Just a suggestion.
I would be happy to help if pointed with some resources to consume the API.

**Comment by dknowles2** [comment]
This should already be possible. The `changed_by` attribute on a lock should have the data you want. For example, after unlocking with my mobile phone, the state is set to: `mobile device - dknowles`. The "user" portion should either be the username of the account that triggered the unlock, or the name given to the passcode.

There was also some previous discussion about this towards the end of this thread: https://community.home-assistant.io/t/schlage-encode-wifi/108826

If it's not working for you, feel free to shout and I can try and debug.

Cheers!
