### ISSUE TITLE
"Schlage Encode Lock" not showing in integrations

### ISSUE THREAD

**Issue by UncleanTurakina** [dknowles2/ha-schlage#75]
Hi,

I am very new to Home Assistant and this is the first time I have used HACS.  I have carefully followed all the instructions to install HACS and install the haschlage custom repository.  However, when trying to add the Integration, Schlage Encode Lock does not show in the Integrations available to add.  I also scanned the list and have not been able to find it under another name.  Can you suggest any other solutions?

Kind regards,
Ian.

**Comment by dknowles2** [comment]
After adding the Github repo to HACS, you then have to find the integration in HACS and install it. Once that's done, HACS will instruct you to restart your Home Assistant instance, at which point the integration should show up in the Integrations available to add.

**Comment by UncleanTurakina** [comment]
Hi,

Yes, that is what I was expecting however after doing that, what appears to be successfully, the integration is not showing in integrations.  I'm sorry this was unclear in my original enquiry.

Regards,
Ian.

________________________________

**Comment by dknowles2** [comment]
Make sure you've done the following:

1. In HACS, you have to click the "Download" button for the Schlage integration.
2. Restart Home Assistant (`Settings > System > Power button` in the upper-right)
3. Refresh the `Settings > Integrations` page

If that doesn't work, make sure that a `schlage` folder is present under the `custom_components` folder in your Home Assistant installation. HACS should have put it there, but if it didn't, you may need to install it manually.

**Comment by UncleanTurakina** [comment]
Hi Dave,

Many thanks for your help.  "In HACS, you have to click the "Download" button for the Schlage integration." fixed the problem.  It is now working perfectly, although I need to find a better way to geofence, but that's nothing to do with your integration.

It's a great integration.

Thanks,
Ian.
