### ISSUE TITLE
Integration not finding my lock

### ISSUE THREAD

**Issue by paulearley** [dknowles2/ha-schlage#77]
This cloud integration is not finding my lock. I copied the contents of the zip file  "custom_components" folder to my custom_components folder, completed a full restart of HA, and ensured the settings included "Enable newly added entities." I am able to access my lock from the Schlage app on my iPhone and all works from that app. I am using the latest version of HA (Just updated to the latest today - 5/34/2023).  To be sure I restarted HA again and reloaded the integration again when that did not solve the problem. 

My lock is a Schlage Encore Plus

Any suggestions?  Thanks for your work on this.

**Comment by dknowles2** [comment]
Did you also add the integration to HA? You need to go to `Settings > Devices & Services` and then click the `Add Integration` button like you would with any other integration. From there you can add the Schlage integration and login to your Schlage account, which should find your locks.

**Comment by silvadiegoa** [comment]
I think I have the same issue, and possibily because we have the lock in homekit using thread/bluetooth. Have you tried to connect the lock via wifi (doing it first via schlage app)? I haven't tried yet on mine, I am testing how the lock works without wifi atm.

**Comment by 1Humza** [comment]
This integration will only work if lock is using WiFi. Hopefully bluetooth / thread support is possible..

**Comment by Lampornis** [comment]
For what it is worth I have the same issue.  Both my locks have an IP address and are connected to my router, but they are clearly communicating with Apple Home via Thread and are listed as part of my Thread network.  Hopefully a way around this can be found.

**Comment by dknowles2** [comment]
The Encode Plus locks seem to behave differently if you set them up via Thread or HomeKit. 

I don't have access to one of those locks to test on, so I'm not sure how much I can help. Bluetooth support is also on my bucket list, but the protocol is very difficult to reverse engineer and I haven't had time to spend on it. (It also may have changed with the Plus models)
