### ISSUE TITLE
Only 1 of 2 Encode Plus locks showing "Changed By" attribute.

### ISSUE THREAD

**Issue by millercentral** [dknowles2/ha-schlage#79]
So this is a strange one. In my house I have two identical Encode Plus locks. The integration shows both devices and lock/unlock works great for both. 

I just recently noticed however that only the "Kitchen Lock" (which is the "first" lock in the slide list in the Schlage app if that matters) shows the "Changed By" attribute in logbook/device events, the second lock, "Front Door", does not appear to have the Changed By attribute (though changed by is visible in the Schlage app for that lock). Here is a screenshot example:

![Kitchen Door Lock](https://github.com/dknowles2/ha-schlage/assets/7720102/09ecfcf6-52aa-4d67-a37e-c3ce64fcb402)
![Front Door Lock](https://github.com/dknowles2/ha-schlage/assets/7720102/2246a832-d90d-4592-a3a9-2a5310695795)

Is there some configuration detail I missed with the front door lock that enables that attribute (I don't see any). As far as I can tell, every other aspect of the two locks (firmware, model number, etc) is identical. 

Thanks for any insight!

**Comment by dknowles2** [comment]
Is there anything in the Home Assistant logs? (`Settings > System > Logs`)

If there's no changed by, then either there was some failure reading lock logs from Schlage or there wasn't a log entry related to lock state changing found in what we read.

**Comment by millercentral** [comment]
I'm not seeing any related logs for the component, but maybe I have the logger set wrong. I'll poke around and see what I can find.

**Comment by millercentral** [comment]
Okay, final update. When using an automation, this appears to be working correctly, only the logbook in the device page is reporting history incorrectly. I don't know why the lock previously wasn't showing a changed_by attribute, but since rebooting HA, that is no longer repo-ing, so I'm going to close this.

The only remaining bummer (which is a Schlage problem, not an issue with this component), is that it does not appear to identify the user when unlocking with Apple Home Key, it only says "Apple home key". 

Thank you again for the work on this component and the ongoing support. It is very useful to my Home Assistant experience!
