### ISSUE TITLE
Invalid Handler Specified upon installation

### ISSUE THREAD

**Issue by tool172** [dknowles2/ha-schlage#82]
"Invalid Handler specified" on the install page on devices and integrations in HA.

**Comment by tool172** [comment]
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by dknowles2** [comment]
Looking at reports of this error from other integrations, I think this is a problem with Home Assistant not installing python dependencies correctly. I'd suggest uninstalling the integration, restarting Home Assistant, and then trying again from scratch and hoping it does the install correctly.

I don't think there's much I can do on the integration side to help, as this is an error from within the core of Home Assistant. ☹️
